config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#index'

  get :signin, to: 'sessions#new', as: :signin
  resources :sessions, only: :create
  delete :signout, to: 'sessions#destroy', as: :signout

  get :signup, to: 'users#new', as: :signup
  resources :users, only: :create

  resources :projects

  resources :projects_users, only: [:create, :destroy]
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true, optional: true

  validates :state, length: { maximum: 2 }
  validates :street, :city, :state, :zip, presence: true
  validates :zip, numericality: { only_integer: true }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :projects
  has_one :address, as: :addressable, dependent: :destroy
  validates :name, uniqueness: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company
  has_many :projects_users
  has_many :users, through: :projects_users
  has_one :address, as: :addressable, dependent: :destroy

  validates :name, :description, presence: true
  validates :name, uniqueness: true

  accepts_nested_attributes_for :address
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :user_id, uniqueness: {
    scope: :project_id,
    message: 'The user is already assigned to the project'
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :company
  has_many :projects_users
  has_many :projects, through: :projects_users

  validates :username, :email, presence: true, uniqueness: true
  validates :email, format: { with: /\w@\w/ }
end

app/models/weather.rb
class Weather
  def self.get_weather(zip)
    response = HTTParty.get("http://api.openweathermap.org/data/2.5/weather?zip=#{zip},us&APPID=#{ENV['WEATHER_KEY']}")
    parsed_response = response.parsed_response
    description = parsed_response["weather"][0]["description"]
    temp = to_farenheit(parsed_response["main"]["temp"])
    {description: description,
      temp: temp,
      image: image(description)}
  rescue
    {}
  end

  def self.to_farenheit(kelvin)
    (kelvin*9/5 - 459.67).round.to_s + '°';
  end

  def self.image(description)
    if description.include?('rain')
      "rain.png"
    elsif description.include?('snow')
      "snow.png"
    else
      "sun.png"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def auth_user
    if current_user.blank?
      redirect_to root_path if current_user.blank?
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :auth_user

 def index
    if current_user.admin?
      @projects = current_user.company.projects
    else
      @projects = current_user.projects
    end
  end

  def new
    if current_user.admin?
      @project = current_user.projects.new
    else
      redirect to projects_path
    end
  end

  def show
    if current_user.admin?
      @project ||= current_user.company.projects.find(params[:id])
      @unassigned_users = current_user.company.users.where.not(id: @project.users.pluck(:id))
    else
      @project ||= current_user.projects.find(params[:id])
    end
      @weather ||= Weather.get_weather(@project.address.zip)
  end

  def create
    @project = current_user.company.projects.new(project_params)
    @project.image_url = 'placeholder_project.photo.png'
    if @project.save
      flash[:success] = 'The project was added'
      redirect_to projects_path
    else
      flash[:notice] = 'Check the error messages and try again'
      render :new
    end
  end

  def edit
    @project = current_user.company.projects.find(params[:id])
  end

  def update
    @project = current_user.company.projects.find(params[:id])
    if @project.update(project_params)
      flash[:success] = 'The project was updated'
      redirect_to project_path(@project.id)
    else
      flash[:notice] = 'Check the error messages and try again'
      render :edit
    end
  end

  def destroy
    current_user.company.projects.find(params[:id]).destroy
    redirect_to projects_path, notice: 'The project was deleted!'
  end

  private

  def project_params
    params.require(:project).permit(
      :name,
      :description,
      address_attributes: [:street, :city, :state, :zip]
    )
  end
end

app/controllers/projects_users_controller.rb
class ProjectsUsersController < ApplicationController
  before_action :auth_user

  def create
    @projects_user = ProjectsUser.create(project_id: params[:format], user_id: params[:user_id])
    redirect_to project_path(params[:format])
  end

  def destroy
    Project.find(params[:id]).users.delete(User.find(params[:user_id]))
    redirect_to project_path(params[:id]), notice: 'The person was unassigned!'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    redirect_to projects_path if current_user
  end

  def new; end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = 'Welcome back'
      redirect_to projects_path
    else
      flash[:notice] = 'Please try again'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :user
  attr_reader :user

  def new
    @user = User.new
    @companies = Company.all
  end

  def create
    @user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:success] = 'Welcome to Build Better: You are logged in!'
      redirect_to projects_path
    else
      flash[:notice] = 'Check the error messages and try again!'
      @companies = Company.all
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :company_id,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(email)
    hashed_email = Digest::MD5.hexdigest(email.downcase.strip)
    image_tag "http://www.gravatar.com/avatar/#{hashed_email}?s=50.jpg", alt: 'Profile Photo'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Construction Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="main-wrapper">
    <header>
      <% if current_user %>
        <%= link_to image_tag('logo.png'), projects_path %>
        <div><%= link_to "Sign Out", signout_path, method: :delete %></div>
        <h1><%= current_user.company.name %></h1>
      <% else %>
        <%= link_to image_tag('logo.png'), root_path %>
      <% end %>
    </header>

    <% if flash[:notice] %>
      <div class="flash-notice">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:success] %>
      <div class="flash-success">
        <%= flash[:success] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= render partial: 'shared/form_errors', locals: { form: @project } %>

<div class="center">
  <%= form_for @project do |f| %>
    <%= f.label :name, nil, class: "left" %>
    <%= f.text_field :name, placeholder: 'Animal Store' %>
    <%= f.label :description, nil, class: "left" %>
    <%= f.text_area :description, placeholder: 'describe the project', rows: 8 %>
    <%= f.label :address, nil, class: "left" %>
    <%= f.fields_for :address, @project.address || @project.build_address do |address| %>
      <%= address.text_field :street, placeholder: '123 Main Streen' %>
      <%= address.label :city, nil, class: "left" %>
      <%= address.text_field :city, placeholder: 'Rockville' %>
      <%= address.label :state, nil, class: "left" %>
      <%= address.text_field :state, placeholder: 'MD' %>
      <%= address.label :zip, nil, class: "left" %>
      <%= address.text_field :zip, placeholder: '20983' %>
    <% end %>
    <%= f.submit %>
  <% end %>
</div>

app/views/projects/_project_info.html.erb
<div class="project">
  <%= link_to image_tag(project.image_url), project_path(project) %>
  <div class="text">
    <h1><%= project.name %></h1>
    <div class="address">
      <div><%= project.address.street %></div>
      <div><%= project.address.city %>, <%= project.address.state %>, <%= project.address.zip %></div>
     </div>
     <div><%= project.description %></div>
  </div>
</div>

app/views/projects/edit.html.erb
<%= render partial: 'form' %>

app/views/projects/index.html.erb
<% if @projects.empty? %>
  <div>You're not assigned to any projects yet.</div>
<% end %>

<div class="project-info">
  <% @projects.each do |project| %>
    <%= render partial: 'project_info', locals: { project: project } %>
  <% end %>
</div>

<% if current_user.admin? %>
  <button class="add-new"><%= link_to "Add New Project", new_project_path %></button>
<% end %>

app/views/projects/new.html.erb
<%= render partial: 'form' %>

app/views/projects/show.html.erb
 <% if current_user.admin? %>
  <div class="edit">
    <button><%= link_to "Edit Project ", edit_project_path(@project) %></button>
  </div>
<% end %>

<% if current_user.admin? %>
  <%= form_tag project_path(@project), method: "DELETE" do %>
  <%= submit_tag "Delete Project", data: {confirm: "Are you sure?"}, class: "danger" %>
  <% end %>
<% end %>

<div class="project-info">
  <%= render partial: 'project_info', locals: { project: @project } %>
</div>

<div class="group">
  <% if @weather.present? %>
    <div class="weather">
      <div>Current Weather</div>
      <%= image_tag(@weather[:image]) %>
      <div><%= @weather[:temp] %></div>
      <div><%= @weather[:description] %></div>
    </div>
<% end %>

<% if current_user.admin? && @unassigned_users.present? %>
  <div class="add-people">
    <div> Add people to the project</div>
    <%= form_tag projects_users_path(@project) do %>
      <%= select_tag :user_id, options_from_collection_for_select(@unassigned_users, :id, :username) %>
      <%= submit_tag "Add" %>
     <% end %>
   </div>
 <% end %>
</div>

<hr>

<% if @project.users.present? %>
  <div class="assigned-ppl">
    <h2>People assigned to the project:</h2>
    <% @project.users.each do |user| %>
      <div class="person">
        <%= gravatar_for(user.email) %>
        <div><%= user.username %></div>
        <div class="email"><%= user.email %></div>
        <% if current_user.admin? %>
          <%= form_tag projects_user_path(@project), method: "DELETE" do %>
          <%= hidden_field_tag :user_id, user.id %>
          <%= submit_tag "x", data: {confirm: "You're unassigning #{user.username.capitalize}, are you sure?"}, class: "danger delete-person" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.errors.any? %>
  <ul class="center">
    <% form.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<%= render partial: 'shared/form_errors', locals: { form: user } %>

<div class="center">
  <%= form_for user do |f| %>
    <%= label_tag :username, nil, class: "left" %>
    <%= f.text_field :username, placeholder: 'username' %>
    <%= label_tag :email, nil, class: "left" %>
    <%= f.text_field :email, placeholder: 'email' %>
    <%= label_tag 'Choose Company', nil, class: "left" %>
    <%= f.select :company_id, options_from_collection_for_select(@companies, :id, :name) %>
    <%= label_tag :password, nil, class: "left" %>
    <%= f.password_field :password, placeholder: 'password' %>
    <%= label_tag :password, nil, class: "left" %>
    <%= f.password_field :password_confirmation, placeholder: 'retype password' %>
    <%= f.submit %>
  <% end %>
</div>